version: '2'
services:
  app:
    build: 
      args:
        user: web-user
        uid: 197609
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app
networks:
  app:
    driver: bridge